### ISSUE TITLE
Amazing!

### ISSUE THREAD

**Issue by benjamingr** [aemkei/world#1]
Very interesting. Just wanted to let you know about http://stackoverflow.com/q/18834309/1348195 and that you might want to add your annotated source there as an answer (because since you specified no copyright, no one else can ;))

Anyway, great work! Starting. Feel free to close this issue after reading.

**Comment by aemkei** [comment]
Thanks for the hint!

Just added the source:
http://stackoverflow.com/questions/18834309/how-does-this-obfuscated-javascript-work/18964424#18964424

On Mon, Sep 23, 2013 at 4:09 PM, benjamingr notifications@github.comwrote:

> Very interesting. Just wanted to let you know about
> http://stackoverflow.com/q/18834309/1348195 and that you might want to
> add your annotated source there as an answer (because since you specified
> no copyright, no one else can ;))
> 
> Anyway, great work! Starting. Feel free to close this issue after reading.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aemkei/world/issues/1
> .

## 

Martin Kleppe
Head of Development

Ubilabs GmbH
Juliusstraße 25
22769 Hamburg, Germany

kleppe@ubilabs.net
http://www.ubilabs.net/

Tel. +49 (0) 40 - 60 94 661-81
Fax +49 (0) 40 - 60 94 661-66

http://www.xing.com/profile/Martin_Kleppe

Handelsregister Hamburg: HRB 110269
Steuernummer: 46/765/01253
Geschäftsführer: Michael Pletziger, Jens Wille

**Comment by benjamingr** [comment]
Heh, seeing this is open almost two years later :D See you on Monday.
